version: "3"

networks:
  corp:
    driver: bridge

services:
  web:
    container_name: angular-tuned
    networks:
      - corp
    build: .
    volumes:
      - ./dist:/usr/share/nginx/html/dist
      - ./dist:/var/www/html/dist
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
